### ISSUE TITLE
[ error ] Cannot find module './lib'

### ISSUE THREAD

**Issue by ThisMe124** [ppeeou/ping-tcp-js#14]
I want to ask, how do I fix this?, 
here I use Vercel.

![Screenshot_20240211-102211](https://github.com/ppeeou/ping-tcp-js/assets/88891071/b0da2584-05b3-4016-b9f9-9f8abf7ee136)

**Comment by ppeeou** [comment]
Thank you for your interest in our library

Because it was a library created a long time ago, it did not support types and properly supported esm and commonjs environments.

Could you please use version 2.0.2 according to the package you are using?
```
npm i ping-tcp-js@2.0.2
// or
yarn i ping-tcp-js@2.0.2
// or
pnpm i ping-tcp-js@2.0.2
```

When changing to TypeScript in version 2, the existing interface was changed.
I think it would be a good idea to check and work on it. Thank you.

https://github.com/ppeeou/ping-tcp-js?tab=readme-ov-file#ping

@ThisMe124

**Comment by ThisMe124** [comment]
> Thank you for your interest in our library
> 
> Because it was a library created a long time ago, it did not support types and properly supported esm and commonjs environments.
> 
> Could you please use version 2.0.2 according to the package you are using?
> 
> ```
> npm i ping-tcp-js@2.0.2
> // or
> yarn i ping-tcp-js@2.0.2
> // or
> pnpm i ping-tcp-js@2.0.2
> ```
> 
> When changing to TypeScript in version 2, the existing interface was changed. I think it would be a good idea to check and work on it. Thank you.
> 
> https://github.com/ppeeou/ping-tcp-js?tab=readme-ov-file#ping
> 
> @ThisMe124

the error is the same as that

![Screenshot_20240215-085620](https://github.com/ppeeou/ping-tcp-js/assets/88891071/438e4bb0-220f-4531-b673-b76059f9a6f3)

**Comment by ppeeou** [comment]
Could you let me know version??(ping-tcp-js)

@ThisMe124

**Comment by ThisMe124** [comment]
> Could you let me know version??(ping-tcp-js)
> 
> @ThisMe124

I have replaced it with the version provided, namely v2.0.2

**Comment by ppeeou** [comment]
@ThisMe124 

Could you please use 2.0.4?
The wrong file was distributed together.

[link](https://codesandbox.io/p/devbox/ping-dty3wv?file=%2Fapp%2Fpage.tsx%3A14%2C2&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsrdsvp000073b6opg0rqnu7%2522%252C%2522sizes%2522%253A%255B52.175925925925924%252C47.824074074074076%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsrdsvp000023b6ohu9oppv1%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsrdsvp000043b6optstaajo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsrdsvp000063b6o6nqqd5bj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsrdsvp000023b6ohu9oppv1%2522%253A%257B%2522id%2522%253A%2522clsrdsvp000023b6ohu9oppv1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsre2c2100023b6oxhzk2c4e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A2%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A2%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsre2c2100023b6oxhzk2c4e%2522%257D%252C%2522clsrdsvp000063b6o6nqqd5bj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsrdsvp000053b6oxs2fesge%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsrdsvp000063b6o6nqqd5bj%2522%252C%2522activeTabId%2522%253A%2522clsrdsvp000053b6oxs2fesge%2522%257D%252C%2522clsrdsvp000043b6optstaajo%2522%253A%257B%2522id%2522%253A%2522clsrdsvp000043b6optstaajo%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsrdsvp000033b6oqhpqe0p8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsrdsvp000033b6oqhpqe0p8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by ThisMe124** [comment]
> @ThisMe124
> 
> Could you please use 2.0.4? The wrong file was distributed together.
> 
> Below are the test results when used in nextjs.
> 
> [link](https://codesandbox.io/p/devbox/ping-dty3wv?file=%2Fapp%2Fpage.tsx%3A14%2C2&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsrdsvp000073b6opg0rqnu7%2522%252C%2522sizes%2522%253A%255B52.175925925925924%252C47.824074074074076%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsrdsvp000023b6ohu9oppv1%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsrdsvp000043b6optstaajo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsrdsvp000063b6o6nqqd5bj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsrdsvp000023b6ohu9oppv1%2522%253A%257B%2522id%2522%253A%2522clsrdsvp000023b6ohu9oppv1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsre2c2100023b6oxhzk2c4e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A2%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A2%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsre2c2100023b6oxhzk2c4e%2522%257D%252C%2522clsrdsvp000063b6o6nqqd5bj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsrdsvp000053b6oxs2fesge%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsrdsvp000063b6o6nqqd5bj%2522%252C%2522activeTabId%2522%253A%2522clsrdsvp000053b6oxs2fesge%2522%257D%252C%2522clsrdsvp000043b6optstaajo%2522%253A%257B%2522id%2522%253A%2522clsrdsvp000043b6optstaajo%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsrdsvp000033b6oqhpqe0p8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsrdsvp000033b6oqhpqe0p8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Ah its working that version v2.0.4 😁 thx for reply
